config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  authenticated do
    root :to => 'contacts#index'
    get 'contacts/index', as: 'contacts'
    get 'contacts/new', as: 'new_contact'
    post 'contacts/index', to: 'contacts#create'
  end

  root to: 'visitors#index'
  get  '/about', to: 'pages#about'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  require 'digest/md5'
  belongs_to :group, :autosave => true
   paginates_per 10
   validates :name , :email, presence: true
   validates :name, length: {minimum: 2}
  def gravater
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"

  end
end

app/models/group.rb
class Group < ApplicationRecord
has_many :contacts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
              def gravater
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
   # before_action :authenticate_user!


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    contact_groups
    end


  def new
    @contact = Contact.new
    contact_groups
  end

  def create
    # params[:group_id] = params[:group]['group_id']

    @contact =Contact.new(contact_params)
    if @contact.save
      flash[:success] = "contact was successfully created."
      redirect_to contacts_path
    else
      contact_groups
      render 'new'
    end
  end


private


def contact_params
  params.require(:contact).permit(:name, :email, :company, :address, :phone, :group_id)

end

  def contact_groups
    if params[:group_id] && !params[:group_id].empty?
      # @contacts =Contact.where(group_id: params[:group_id]).page(params[:page])
      @contacts = Group.find(params[:group_id]).contacts.page(params[:page])
    else
      @contacts = Contact.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravater
    hash = Digest::MD5.hexdigest(current_user.email.to_s.downcase)
    "https://www.gravatar.com/avatar/#{hash}"

  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
         <tr>
              <td class="middle">
                <div class="media">
                  <div class="media-left">
                    <a href="#">
                      <%= image_tag contact.gravater, class: "media-object" %>
                      </a>
                    </div>
                    <div class="media-body">
                      <h4 class="media-heading text-light"><%= contact.name %></h4>
                      <address>
                        <strong class="light-text"><%= contact.company%></strong>
                        <br class="light-text">
                        <%= contact.email%>
                        </address>
                      </div>
                    </div>
                  </td>
                  <td width="100" class="middle">
                    <div>
                      <a href="#" class=" btn-circle " title="Edit">
                        <i class="ion-ios-compose-outline text-success "></i>
                      </a>
                      <a href="#" class="btn-circle " title="Edit">
                        <i class="ion-ios-trash-outline  text-secondary"></i>
                      </a>
                    </div>
                  </td>
                </tr>

app/views/contacts/_form.html.erb
<%= render 'layouts/sidenav' %>
<!-- content -->
<div class=" contacts-outer">
  <div class="container">
    <div class="row">
      <div class="col-md-3"><%= render 'layouts/mainsidenav' %>
      </div>
      <div class="col-md-9 mt-4">
        <%= form_with(model: contact, local: true) do |form| %> <!-- start of form to add new contact -->

          <div class="panel panel-default special-color form-panel">

              <div class="panel-body special-color">
                <div class="row">
                  <div class="col-md-8"><% if @contact.errors.any? %>
                    <div class="alert alert-danger">
                      <h4>Please correct the following errors:</h4>
                      <ul><% @contact.errors.full_messages.each do |message| %>
                        <li><%= message %>
                        </li>
                      </ul><% end %>
                    </div><% end %>
                  </div>
                </div>
                <div class="form-horizontal">
                  <div class="row">
                    <div class="col-md-6 no-gutters mr-1 pr-1">
                      <div class="form-group">
                        <label for="name" class="control-label col-md-3 white-text">Name</label>
                        <div class="col-md-12">
                          <%= form.text_field :name, id: :contact_name, class: 'form-control rounded-0' %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label for="company" class="control-label col-md-3 white-text">Company</label>
                          <div class="col-md-12">
                             <%= form.text_field :company, id: :contact_company, class: 'form-control rounded-0' %>
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="email" class="control-label col-md-3 white-text">Email</label>
                            <div class="col-md-12">
                               <%= form.text_field :email, id: :contact_email, class: 'form-control rounded-0' %>
                              </div>
                            </div>
                            <div class="form-group">
                              <label for="phone" class="control-label col-md-3 white-text">Phone</label>
                              <div class="col-md-12">
                                <%= form.text_field :phone, id: :contact_phone, class: 'form-control rounded-0' %>
                                </div>
                              </div>
                              <div class="form-group">
                                <label for="name" class="control-label col-md-3 white-text">Address</label>
                                <div class="col-md-12">
                                      <%= form.text_area :address, id: :contact_address, class: 'form-control rounded-0', row: '3' %>

                                </div>
                              </div>
                            </div>
                            <div class="col-md-5 form-right no-gutters ml-0 pl-0 mr-0 pr-0">
                              <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="row">
                                  <div class="col-md-6 pl-4 ">
                                    <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                                      <img src="http://placehold.it/150x150" alt="Photo">
                                      </div>
                                    </div>
                                    <div class="col-md-6">
                                      <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                      <div class="text-center">
                                        <span class="btn default-color-dark btn-file rounded-0">
                                          <span class="fileinput-new">Choose Photo</span>
                                          <span class="fileinput-exists">Change</span>
                                          <input type="file" name="...">
                                          </span>
                                          <a href="#" class="btn btn-danger fileinput-exists rounded-0" data-dismiss="fileinput">Remove</a>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <div class="col-md-12  mt-4  mr-0 pr-0">
                                      <div class="pt-3">
                                      <select name="contact[group_id]" class="form-control bg-dark mb-4 rounded-0">
                                      <option value="0">Select Group</option>
                                      <% Group.all.each do |group| %>
                                      <option value="<%=group.id%>"><%= group.name %></option>
                                      <% end %>
                                      </div>
                                    </div>
                                    <div class="col-md-12">
                                      <div class="row">
                                        <div class="col-md-12 mt-4  pr-0">
                                          <a href="#" id="add-group-btn" class="btn mt-4  btn bg-dark mt-2 btn-block rounded-0">+ Group</a>
                                        </div>
                                        <div class="col-md-12 mt-4 pr-0" >
                                          <div class="input-group mb-3">
                                            <input type="text" name="" id="" class="form-control rounded-0  " placeholder="Type group name">
                                              <div class="input-group-append">
                                                <span class="input-group-text rounded-0 bg-secondary border-0" id="basic-addon2 ">
                                                  <i class="ion-android-done white-text "></i>
                                                </span>
                                              </div>
                                            </div>
                                          </div>
                                          <div class="panel-footer">
                                            <div class="col-md-12">

                                              <div class="row  mt-4">
                                                <div class="col">
                                                  <button type="submit" class="btn default-color-dark rounded-0">Save New Contact</button>
                                                </div>
                                                <div class="col">
                                                  <a href="#" class="btn  btn-danger  ml-0  deep-orange-text rounded-0" style="min-width: 100%;">Cancel</a>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </<% end %>>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<%= render 'layouts/sidenav' %>
<!-- content -->
<div class=" contacts-outer">
  <div class="container">

    <div class="row main-section">
      <div class="col-lg-3"><%= render 'layouts/mainsidenav' %>
      </div>
      <!-- /.col-md-3 -->
      <div class="col-lg-9 main-content-dash">
       <span><h3 class="main-head"> Contacts</h3>

        <%= link_to new_contact_path, class: "btn add-c float-right" do %>
          <i class="ion-android-add"></i>
          add contact
         <%end %>
        </span>
        <% if @contacts.blank? %>
             <div class="alert alert-warning" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <strong> record not found </strong>
            </div>
        <%end %>
        <div class="panel panel-default">
          <table class="table">
            <%= render @contacts %>

            </table>
                </div>
                <div class="text-center">
                  <%= paginate @contacts%>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name,:</strong>
  <%= @contact.name, %>
</p>

<p>
  <strong>Email,:</strong>
  <%= @contact.email, %>
</p>

<p>
  <strong>Company,:</strong>
  <%= @contact.company, %>
</p>

<p>
  <strong>Address,:</strong>
  <%= @contact.address, %>
</p>

<p>
  <strong>Phone,:</strong>
  <%= @contact.phone, %>
</p>

<p>
  <strong>Cell,:</strong>
  <%= @contact.cell, %>
</p>

<p>
  <strong>Group:</strong>
  <%= @contact.group_id %>
</p>

<p>
  <strong>New:</strong>
  <%= @contact.new %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_dropdown.html.erb
<%= link_to 'About', page_path('about'), class: 'dropdown-item' %>
<% if user_signed_in? %>
<%= link_to 'Edit account', edit_user_registration_path, class: 'dropdown-item' %>
<%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'dropdown-item' %>
<% else %>
<%= link_to 'Sign in', new_user_session_path, class: 'dropdown-item' %>
<%= link_to 'Sign up', new_user_registration_path, class: 'dropdown-item' %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>   <%= link_to "Didn't get the email?", new_confirmation_path(resource_name), class: 'dropdown-item' %>
<% end -%></li>
<% end %>
<% if user_signed_in? %>
<%= link_to 'Users', users_path, class: 'dropdown-item' %>
<% end %>

app/views/layouts/_lowernavbar.html.erb
<nav class="navbar navbar-expand-md navbar-light" id="lower-n">
  <div class="container-fluid pl-0 pr-0">
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto pc-menu ml-0 pl-0" id="lower-nv-links">
          <li class='nav-item'> <%= link_to 'Home', root_path, class: 'nav-link dropdown-item font-weight-light blue-grey-text' %></li>
          <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link dropdown-item font-weight-light blue-grey-text' %></li>
      </ul>

      </div>
    </div>
  </nav>

app/views/layouts/_mainsidenav.html.erb
<div class="list-group main-side" >
<div class="card card-nav-tabs" ">
  <div class="card-header card-header-danger">
    Contacts
  </div>

   <div class="list-group-item special-color list-group-flush black-text  mr-0 pr-2">All Contacts and groups <small class=" i-right"><i class="ion-android-menu"></i></small></div>
       <%= link_to contacts_path, class: "list-group-item list-group-item-action flex-column align-items-start bg-dark mr-0 pr-0" do %>
      <ul class="list-inline mr-0 pr-0">
         <li class="list-inline-item mr-0 pr-0"><h5 class="mb-1 text-light mr-0 pr-0">All Contacts</h5></li>
         <li class="list-inline-item mr-0 pr-0"><small class="text-light badge badge-pill p-0 f-right mr-0 pr-0"><%= @contacts.count %> </small></li>
      </ul>
      <% end %>
      <% Group.all.each do |group| %>
      <% active = params[:group_id].to_i == group.id  ? 'current-link' : 'bg-dark' %>
      <%= link_to  contacts_path(group_id: group.id), class: "list-group-item list-group-item-action flex-column align-items-start bg-dark mr-0 pr-0 #{active} " do %>
       <ul class="list-inline mr-0 pr-0">
         <li class="list-inline-item mr-0 pr-0"><h5 class="mb-1 text-light mr-0 pr-0"><%= group.name %></h5></li>
         <li class="list-inline-item mr-0 pr-0"><small class="text-light badge badge-pill p-0 f-right mr-0 pr-0"><%= group.contacts.count %>  </small></li>
      </ul>
    <% end %>
  <% end %>
</div>


</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
      <div class="alert alert-with-icon alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert" onload="this.showNotification('top','right')" data-notify="container">
      <i class="material-icons" data-notify="icon">notifications</i>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="material-icons">close</i>
      </button>
      <span data-notify="icon" class="now-ui-icons ui-1_bell-53"></span>
      <span data-notify="message"><%= content_tag :div, msg, :id => "flash_#{name}" %></span>
    </div>



  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'> <%= link_to 'Home', root_path, class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'> <%= link_to 'About', page_path('about'), class: 'nav-link dropdown-item font-weight-light info-text' %></li>


<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link dropdown-item font-weight-light info-text' %></li>
  <li class='nav-item'> <%- if devise_mapping.confirmable? && controller_name != 'confirmations font-weight-light info-text' %>   </li>
  <li>  <%= link_to "Didn't get the email?", new_confirmation_path(resource_name), class: 'nav-link dropdown-item info-text' %>
<% end %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
      <div class="container">
      <a class="navbar-brand ml-0 pl-0" href="/"><%= link_to 'Hudson Lab', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class='nav-item'><%= link_to 'Account', edit_user_registration_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link ' %></li>
          <li class='nav-item'> <%= link_to 'About', page_path('about'), class: 'nav-link' %></li>
        </ul>
        <form class="form-inline ml-auto">
            <div class="form-group has-white bmd-form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-white btn-raised btn-fab btn-fab-mini btn-round">
                <i class="fa fa-search"></i>
            </button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>


    <li class="nav-item dropdown pull-right">
            <a class="nav-link dropdown-toggle mr-3 mr-lg-0" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ion-android-menu light-text"></i>

            </a>
            <div class="dropdown-menu dropdown-menu-right   " aria-labelledby="navbarDropdownMenuLink">
              <ul> <li  class='nav-item'>  <a href="/" title="home" class="ml-3 nav-link dropdown-item">Home</a></li>
               <%= render 'layouts/dropdown' %></ul>
            </div>
        </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hudson Contacts" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hudson Contacts" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
      <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  </head>
  <body>
    <div class="wrapper">
    <% if user_signed_in? %>
      <div class="main-panel">
        <%= render 'layouts/navigation' %>

    <%end%>
    <%= render 'layouts/messages' if !flash.empty? %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<div class="margin-top">
  <style type="text/css">
  .about-sec {
    width: 100%;
    background-color: white !important;
    min-height: 100vh !important;
    padding-top: 80px;
  }
.main-doc-sec {
    padding: 10px;
}
</style>
</div>
<div class=" about-sec">
  <div class=" container main-doc-sec ">
    <div class="row ">
      <div class="col-md-4">
        <ul class="list-group">
          <li class="list-group-item  bg-dark text-light d-flex justify-content-between align-items-center">
        Our Documation

            <span class="badge  badge-info badge-pill">4 topics</span>
          </li>
        </ul>
        <div class="row">
          <div class="col-12">
            <div class="list-group rounded-0 mt-4" id="list-tab" role="tablist">
              <a class="list-group-item list-group-item-action bg-dark text-light" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">How To Add Contacts</a>
              <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">How To Delete Contacts</a>
              <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">How To Share Contacts</a>
              <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">How To Use Settings</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <h1>Hudson Lab</h1>
        <br>
          <br>
            <br>
              <h5>This app is a full stack contact manager application which Hudson Commercial Employees, so they can easily manage their contacts.</h5>
            </div>
          </div>
        </div>
      </div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="landding-page">
  <div class="layer">
    <!-- Page Content -->
    <section filter-color="orange ">
      <center>
        <div class="top-header">
          <!--  render 'layouts/messages'  -->
          <div class="text-center main-brand ">
            <div class="" >
              <div class="">
                <strong>
                  <h1 class="title white-text"  style="color: white !important;">
                    The Hudson Commercial
                  </h1>
                </strong>
                <h3 class="description white-text" style="color: white !important;">Dashbord CRM</h3>
                <br/>
                <a id="sign_up" href="/users/sign_up" class="btn btn-outline-light btn-round btn-lg">Lets do this get started</a>
              </div>
            </div>
          </div>
        </div>
      </center>
    </section>
  </div>
</div>